version: "3"

services:

  auth: &auth
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./docker/variables.env
    command: ./docker-entrypoint.sh
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - auth_db
      - billing_db
      - storage

  auth_kafka_consumer:
    <<: *auth
    depends_on:
      - kafka
      - zookeeper
    ports: [ ]
    command: ./start-kafka-consumer.sh
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092

  auth_db:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/variables.env
    ports:
      - "5433:5432"

  billing:
    build: ./billing_service
    container_name: billing
    command: ./docker-entrypoint.sh
    env_file:
      - ./docker/variables.env
    volumes:
      - ./static:/var/www
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - billing_db
      - auth
      - kafka
      - zookeeper

  billing_db:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/variables.env
    ports:
      - "5432:5432"

  storage:
    image: redis:7.0.0-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "billing_user_subscribed:1:1,billing_user_unsubscribed:1:1,billing_subscription_renewal:1:1"

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka

  tests:
    build: ./tests
    entrypoint: /opt/tests/docker-entrypoint.sh
    depends_on:
      - billing
      - auth

  nginx:
    image: nginx:1.23.0
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./static:/var/www
    depends_on:
      - billing
      - auth
    ports:
      - "80:80"

  stripe-webhook:
    image: stripe/stripe-cli:latest
    command: listen --forward-to nginx/api/v1/webhook
    env_file:
      - ./docker/variables.env