version: "3"

services:

  auth:
    build: ./auth_service
    env_file:
      - ./docker/variables.env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - auth_db
      - billing_db
      - storage

  auth_db:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/variables.env
    ports:
      - "5432:5432"

  billing_db:
    image: postgres:14.4
    restart: always
    env_file:
      - ./docker/variables.env
    ports:
      - "5433:5432"

  storage:
    image: redis:7.0.0-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"

