"""empty message

Revision ID: 51d2192079d2
Revises: 8a52a72c7a24
Create Date: 2023-03-18 16:25:57.910524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d2192079d2'
down_revision = '8a52a72c7a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
