"""empty message

Revision ID: e9dc7292f7fd
Revises: 51d2192079d2
Create Date: 2023-03-18 16:27:01.978973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9dc7292f7fd'
down_revision = '51d2192079d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_subscriptions_user_id_fkey', 'user_subscriptions', type_='foreignkey')
    op.drop_column('user_subscriptions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_subscriptions_user_id_fkey', 'user_subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
